#!/usr/bin/env python3
"""One theme, one page shell, for every page the site publishes.

The site is generated by three scripts that grew at different times, and it
looked like it: `render-comparisons.py` had a full design system with dark
mode, an animated hero and a card grid, `render-benchmarks.py` had a smaller
variation on the same idea, and `coverage-dashboard.py` opened its own
stylesheet with a comment calling itself "a deliberately dumb page" -- black
on white, no dark mode, borders at `1px solid #ccc`. A reader moving between
them by the nav links crossed two visual identities in three clicks.

So the tokens and the shell live here and the pages import them. The rule
that follows is the useful part: **a page may add CSS, and may not restate
these.** A colour that appears literally in a page generator is a colour that
will drift from the other two, because nothing makes them move together.

Nothing here is page-specific. The heatmap's cell styling, the dashboard's
bars and the animated architecture diagram all stay with the page that owns
them -- shared means shared, not "everything, somewhere".
"""

from __future__ import annotations

import html

# The palette, in both themes.
#
# `--win`/`--loss`/`--noise` are the semantic good / bad / neither triple, not
# comparison-specific despite the names they were born with: the heatmap uses
# them for a won cell and the coverage dashboard for an implemented endpoint,
# and those should be the same green on the same page furniture.
TOKENS = """
:root {
  --bg: #ffffff; --fg: #1a1a20; --muted: #667; --line: #e2e2ea;
  --card: #f7f7fb; --win-bg: #e7f6ec; --win-fg: #14683a;
  --loss-bg: #fdeaea; --loss-fg: #a02020; --noise-bg: #f0f0f4;
  --noise-fg: #556; --accent: #7c3aed; --accent2: #06b6d4;
  --hero-a: #ede9fe; --hero-b: #cffafe; --shadow: 0 1px 3px rgba(20,20,40,.07);
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #131318; --fg: #e8e8ee; --muted: #99a; --line: #2c2c36;
    --card: #1b1b23; --win-bg: #12301e; --win-fg: #6fd39a;
    --loss-bg: #391616; --loss-fg: #ef9a9a; --noise-bg: #22222c;
    --noise-fg: #99a; --accent: #a78bfa; --accent2: #22d3ee;
    --hero-a: #1e1836; --hero-b: #082f3a; --shadow: 0 1px 3px rgba(0,0,0,.4);
  }
}
"""

# Structure every page shares: the reset, the column, the sticky nav, the
# heading rhythm, tables, cards and chips.
BASE = """
* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body { margin: 0; background: var(--bg); color: var(--fg);
  font: 16px/1.6 system-ui, -apple-system, "Segoe UI", sans-serif; }
main { max-width: 1080px; margin: 0 auto; padding: 0 20px 60px; }
a { color: var(--accent); }

nav { position: sticky; top: 0; z-index: 5;
  padding: 12px 20px; border-bottom: 1px solid var(--line);
  background: color-mix(in srgb, var(--bg) 86%, transparent);
  backdrop-filter: blur(8px); }
nav .inner { max-width: 1080px; margin: 0 auto; width: 100%;
  display: flex; gap: 18px; align-items: baseline; flex-wrap: wrap; }
nav .brand { font-weight: 700; color: var(--accent); margin-right: 4px; }
nav a { color: var(--fg); text-decoration: none; }
nav a:hover { color: var(--accent); }
/* Page-local anchors read as secondary to the site links beside them. */
nav a.sect { color: var(--muted); font-size: .92rem; }
nav a.sect:hover { color: var(--accent); }
/* The current page is stated, not left to be inferred from the URL. */
nav a[aria-current="page"] { color: var(--accent); font-weight: 600;
  box-shadow: inset 0 -2px 0 var(--accent); }

h1, h2, h3 { text-wrap: balance; letter-spacing: -0.01em; }
/* The nav is sticky, so anything an anchor jumps to must clear it or it
   lands underneath and reads as a broken link. */
:target, h2, h3, section[id] { scroll-margin-top: 72px; }
h2 { margin-top: 48px; border-bottom: 1px solid var(--line); padding-bottom: 6px; }

.scroll { overflow-x: auto; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 0.92rem; }
th, td { border: 1px solid var(--line); padding: 6px 9px; text-align: left;
  vertical-align: top; }
th.num, td.num { text-align: right; font-variant-numeric: tabular-nums; }
th { background: var(--card); }

code { background: var(--card); border: 1px solid var(--line);
  padding: .05rem .3rem; border-radius: 4px; font-size: .88em; }

.card { background: var(--card); border: 1px solid var(--line);
  border-radius: 12px; padding: 14px 18px; box-shadow: var(--shadow); }
.chip { padding: 1px 8px; border-radius: 6px; font-size: 0.85rem; }
.chip.win { background: var(--win-bg); color: var(--win-fg); }
.chip.loss { background: var(--loss-bg); color: var(--loss-fg); }
.chip.noise { background: var(--noise-bg); color: var(--noise-fg); }
.legend, .provenance { color: var(--muted); font-size: 0.88rem; }

/* The headline number row, used by every page that has one to show. */
.scoreline { display: flex; gap: 14px; flex-wrap: wrap; margin: 18px 0 0; }
.score { background: color-mix(in srgb, var(--bg) 78%, transparent);
  border: 1px solid var(--line); border-radius: 12px; padding: 10px 18px;
  text-align: center; box-shadow: var(--shadow); }
.score b { display: block; font-size: 1.7rem; font-variant-numeric: tabular-nums; }
.score.win b { color: var(--win-fg); } .score.loss b { color: var(--loss-fg); }
.score.noise b { color: var(--noise-fg); }

/* The shared hero. Pages vary what sits inside it, not what it is. */
.hero { position: relative; overflow: hidden; border-radius: 0 0 18px 18px;
  background: linear-gradient(135deg, var(--hero-a), var(--hero-b));
  padding: 46px 28px 34px; margin: 0 -20px; }
.hero h1 { font-size: clamp(1.9rem, 4.5vw, 2.9rem); margin: 0 0 6px;
  background: linear-gradient(90deg, var(--accent), var(--accent2));
  -webkit-background-clip: text; background-clip: text; color: transparent; }
.hero .sub { color: var(--fg); opacity: .78; max-width: 62ch; margin: 0 0 18px;
  font-size: 1.05rem; }

footer { max-width: 1080px; margin: 0 auto; padding: 24px 20px 40px;
  border-top: 1px solid var(--line); color: var(--muted); font-size: 0.85rem; }
"""

# Line colour per server. Shared because the comparisons charts and any
# future page that names a server should not disagree about which green
# Tuwunel is.
SERVER_COLORS = {
    "spindle": "#7c3aed",
    "synapse": "#e05252",
    "continuwuity": "#d9930d",
    "tuwunel": "#0d9d6d",
}

# The site's pages, in the order the nav lists them. One tuple per page so a
# new page cannot be added to one nav and forgotten in the other two.
PAGES = [
    ("comparisons.html", "Spindle vs the field"),
    ("dashboard.html", "Coverage"),
    ("index.html", "Micro-benchmarks"),
]


def nav(active: str, sections: list[tuple[str, str]] | None = None,
        repository: str = "tuna-os/spindle") -> str:
    """The shared nav, marking whichever page is rendering it.

    `sections` are the current page's own in-page anchors, rendered after a
    separator. They are per-page because they *are* per-page -- a long page
    earns a table of contents and a short one does not -- but the site links
    beside them stay identical everywhere, which is the part that was
    drifting.
    """
    links = []
    for href, label in PAGES:
        current = ' aria-current="page"' if href == active else ""
        links.append(f'<a href="./{href}"{current}>{html.escape(label)}</a>')
    for anchor, label in sections or []:
        links.append(f'<a class="sect" href="{anchor}">{html.escape(label)}</a>')
    # Parameterised for the same reason the footer's link is: this one is
    # generated for whatever repository the page was told about.
    links.append(
        f'<a class="sect" href="https://github.com/{html.escape(repository)}">GitHub</a>'
    )
    inner = "".join(links)
    return f'<nav><div class="inner"><span class="brand">Spindle</span>{inner}</div></nav>'


def head(title: str, extra_css: str = "") -> str:
    """Everything above the body content: meta, title, tokens, base, page CSS."""
    return (
        '<!doctype html>\n<html lang="en">\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{html.escape(title)}</title>\n"
        f"<style>{TOKENS}{BASE}{extra_css}</style>\n"
    )


def footer(note: str = "", repository: str = "tuna-os/spindle") -> str:
    """The shared footer. `note` is per-page provenance, already escaped.

    `repository` is a parameter and not a constant because one page is
    generated for whatever repository it is told about, and the tooling check
    enforces that: the source link was hardcoded once and went on pointing at
    the previous owner from the moment the project moved. A shared footer is
    exactly the place that mistake would come back, so it does not get to
    know the answer on its own.
    """
    source = (
        f'<a href="https://github.com/{html.escape(repository)}">'
        f"{html.escape(repository)}</a>"
    )
    extra = f" · {note}" if note else ""
    return f"<footer>Generated from {source}{extra}</footer>"
