#!/usr/bin/env python3
"""What the Matrix spec asks for that the router does not serve.

    scripts/spec-drift.py                  # rewrite docs/spec-gaps.md
    scripts/spec-drift.py --check          # fail if docs/spec-gaps.md is stale
    scripts/spec-drift.py --spec PATH      # a matrix-spec checkout to read
    scripts/spec-drift.py --preview        # print the report, write nothing

The spec side is every operation in the Client-Server and Server-Server
OpenAPI of the pinned matrix-spec checkout (the same pin openapi-check.py
validates responses against; it is fetched if absent). The server side is
the router, parsed the way the coverage dashboard parses it, so nothing
here is typed. Each spec operation is either served, or listed under the
spec version that introduced it, so the report answers two questions a
maintainer has: "what would it take to claim v1.N" and "what did the last
spec release add that we do not have". Deprecated operations the router
still serves are listed too, since each is a removal waiting to happen.

The report is a generated file, checked in and gated like the dashboard.
That is the point: bumping the spec pin rewrites it, and the diff in that
pull request *is* the list of new work the release brought. Nothing here
gates on the gaps themselves -- a homeserver serves what it serves -- only
on the file telling the truth about them.
"""

from __future__ import annotations

import argparse
import importlib
import pathlib
import re
import subprocess
import sys

import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))
dashboard = importlib.import_module("coverage-dashboard")
openapi = importlib.import_module("openapi-check")

OUT = REPO / "docs" / "spec-gaps.md"
METHODS = ("get", "post", "put", "delete")

# The API directories Spindle *serves*. The application-service and
# push-gateway APIs are ones it calls, and the identity service is a
# different program.
APIS = (("Client-Server", "client-server"), ("Server-Server", "server-server"))


def shape(template: str) -> str:
    """A route template with every placeholder made anonymous, so the spec's
    `{roomId}` and the router's `{room_id}` compare equal."""
    return re.sub(r"\{[^}]+\}", "{}", template.strip()).rstrip("/") or "/"


def spec_operations(root: pathlib.Path, api_dir: str) -> list[dict]:
    """Every (method, template) the spec's OpenAPI defines for one API, with
    the version that added it and whether it is deprecated."""
    out = []
    for file in sorted((root / "data" / "api" / api_dir).glob("*.yaml")):
        with file.open() as handle:
            doc = yaml.safe_load(handle)
        base = "/_matrix/client/v3" if api_dir == "client-server" else "/_matrix/federation/v1"
        for server in doc.get("servers", []):
            variables = server.get("variables", {})
            if "basePath" in variables:
                base = variables["basePath"].get("default", base)
        for path, methods in (doc.get("paths") or {}).items():
            for method, operation in methods.items():
                if method not in METHODS or not isinstance(operation, dict):
                    continue
                out.append(
                    {
                        "method": method.upper(),
                        "template": base + path,
                        "added": str(operation.get("x-addedInMatrixVersion", "")),
                        "deprecated": bool(operation.get("deprecated", False)),
                        "file": file.name,
                    }
                )
    return out


def served() -> set[tuple[str, str]]:
    """(METHOD, shape) for everything the router registers."""
    out = set()
    for path, methods in dashboard.parse_routes():
        for method in methods:
            out.add((method.upper(), shape(path)))
    return out


def version_key(version: str) -> tuple[int, int]:
    match = re.match(r"(\d+)\.(\d+)", version)
    return (int(match.group(1)), int(match.group(2))) if match else (0, 0)


def report(spec_root: pathlib.Path) -> str:
    routes = served()
    served_shapes = {shape for _, shape in routes}
    head = subprocess.run(["git", "-C", str(spec_root), "rev-parse", "HEAD"], capture_output=True, text=True, check=False).stdout.strip()
    pin = head or openapi.SPEC_PIN
    lines = [
        "# Spec gaps",
        "",
        "<!-- Generated by scripts/spec-drift.py. Do not edit by hand. -->",
        "",
        f"Read against [matrix-spec]({openapi.SPEC_URL}) at `{pin[:12]}`"
        + (", the pin" if pin == openapi.SPEC_PIN else f" (the pin is `{openapi.SPEC_PIN[:12]}`; this is a preview)"),
        "`scripts/openapi-check.py` validates responses against. An operation is",
        "*served* when the router registers its method and path; the placeholders",
        "are compared by position, not by name. Bumping the pin rewrites this file,",
        "and the diff is the work the release brought.",
        "",
    ]
    for label, api_dir in APIS:
        operations = spec_operations(spec_root, api_dir)
        missing = [op for op in operations if (op["method"], shape(op["template"])) not in routes]
        present = len(operations) - len(missing)
        deprecated_served = [
            op for op in operations if op["deprecated"] and (op["method"], shape(op["template"])) in routes
        ]
        lines += [f"## {label} API", "", f"{present} of {len(operations)} operations served.", ""]
        by_version: dict[str, list[dict]] = {}
        for op in missing:
            by_version.setdefault(op["added"] or "1.0", []).append(op)
        for version in sorted(by_version, key=version_key):
            ops = by_version[version]
            deprecated_count = sum(1 for op in ops if op["deprecated"])
            heading = f"### Not served, added in v{version}"
            if version == "1.0":
                heading = "### Not served, in the spec since before v1.1"
            lines += [heading, ""]
            if deprecated_count:
                lines += [f"{deprecated_count} of these are deprecated upstream and can stay unserved.", ""]
            for op in sorted(ops, key=lambda o: (o["template"], o["method"])):
                mark = " *(deprecated)*" if op["deprecated"] else ""
                lines.append(f"- `{op['method']} {op['template']}`{mark} — `{op['file']}`")
            lines.append("")
        if deprecated_served:
            lines += ["### Served, but deprecated upstream", ""]
            for op in sorted(deprecated_served, key=lambda o: o["template"]):
                lines.append(f"- `{op['method']} {op['template']}` — `{op['file']}`")
            lines.append("")
    # The other direction: routes the spec at this pin does not name. These
    # are MSCs, admin surfaces and vendor prefixes, and every one should be
    # accounted for by the MSC ledger or an admin doc; the ledger check
    # reads this list.
    spec_shapes = set()
    for _, api_dir in APIS:
        for op in spec_operations(spec_root, api_dir):
            spec_shapes.add(shape(op["template"]))
    extra = sorted(s for s in served_shapes if s not in spec_shapes)
    lines += [
        "## Served beyond the spec at this pin",
        "",
        f"{len(extra)} routes the pinned spec does not define: MSC surfaces under",
        "`unstable/`, the admin and MAS-compatibility APIs, and stable spellings",
        "newer than the pin. Each MSC route must be accounted for in",
        "`contrib/msc/ledger.toml`; `scripts/msc-ledger.py --check` enforces that.",
        "",
    ]
    for path in extra:
        lines.append(f"- `{path}`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--spec", type=pathlib.Path, default=REPO / "tmp" / "matrix-spec")
    parser.add_argument("--check", action="store_true", help="fail if docs/spec-gaps.md is stale")
    parser.add_argument("--preview", action="store_true", help="print the report and write nothing")
    args = parser.parse_args()
    root = openapi.ensure_spec(args.spec)
    text = report(root)
    if args.preview:
        print(text)
        return 0
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"spec-drift: {OUT.relative_to(REPO)} is stale; run scripts/spec-drift.py", file=sys.stderr)
            return 1
        print(f"spec-drift: {OUT.relative_to(REPO)} matches the router and the pinned spec")
        return 0
    OUT.write_text(text)
    print(f"spec-drift: wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
